import { PermissionFlagsBits } from 'discord.js';
import type { RoleConfig } from '../types/index.js';

export const STAFF_ROLES = ['Founder', 'Core Team', 'Developer', 'Moderator', 'Support'];

export const ROLES: RoleConfig[] = [
  {
    name: 'Founder',
    color: '#E74C3C',
    position: 10,
    hoist: true,
    mentionable: false,
    isStaff: true,
    permissions: [PermissionFlagsBits.Administrator],
  },
  {
    name: 'Core Team',
    color: '#E67E22',
    position: 9,
    hoist: true,
    mentionable: false,
    isStaff: true,
    permissions: [
      PermissionFlagsBits.ManageGuild, PermissionFlagsBits.ManageChannels,
      PermissionFlagsBits.ManageRoles, PermissionFlagsBits.ManageMessages,
      PermissionFlagsBits.BanMembers, PermissionFlagsBits.KickMembers,
      PermissionFlagsBits.MuteMembers, PermissionFlagsBits.DeafenMembers,
      PermissionFlagsBits.MoveMembers, PermissionFlagsBits.ManageNicknames,
      PermissionFlagsBits.ViewAuditLog, PermissionFlagsBits.ViewChannel,
      PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks,
      PermissionFlagsBits.AttachFiles, PermissionFlagsBits.ReadMessageHistory,
      PermissionFlagsBits.MentionEveryone, PermissionFlagsBits.Connect,
      PermissionFlagsBits.Speak, PermissionFlagsBits.ManageEvents,
    ],
  },
  {
    name: 'Developer',
    color: '#3498DB',
    position: 8,
    hoist: true,
    mentionable: false,
    isStaff: true,
    permissions: [
      PermissionFlagsBits.ManageChannels, PermissionFlagsBits.ManageMessages,
      PermissionFlagsBits.ViewAuditLog, PermissionFlagsBits.ViewChannel,
      PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks,
      PermissionFlagsBits.AttachFiles, PermissionFlagsBits.ReadMessageHistory,
      PermissionFlagsBits.Connect, PermissionFlagsBits.Speak,
    ],
  },
  {
    name: 'Moderator',
    color: '#2ECC71',
    position: 7,
    hoist: true,
    mentionable: false,
    isStaff: true,
    permissions: [
      PermissionFlagsBits.ManageMessages, PermissionFlagsBits.KickMembers,
      PermissionFlagsBits.BanMembers, PermissionFlagsBits.ManageNicknames,
      PermissionFlagsBits.MuteMembers, PermissionFlagsBits.MoveMembers,
      PermissionFlagsBits.ViewAuditLog, PermissionFlagsBits.ViewChannel,
      PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks,
      PermissionFlagsBits.AttachFiles, PermissionFlagsBits.ReadMessageHistory,
      PermissionFlagsBits.ModerateMembers, PermissionFlagsBits.Connect,
      PermissionFlagsBits.Speak,
    ],
  },
  {
    name: 'Support',
    color: '#1ABC9C',
    position: 6,
    hoist: true,
    mentionable: false,
    isStaff: true,
    permissions: [
      PermissionFlagsBits.ManageMessages, PermissionFlagsBits.ViewChannel,
      PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks,
      PermissionFlagsBits.AttachFiles, PermissionFlagsBits.ReadMessageHistory,
      PermissionFlagsBits.Connect, PermissionFlagsBits.Speak,
    ],
  },
  {
    name: 'Beta Tester',
    color: '#9B59B6',
    position: 5,
    hoist: true,
    mentionable: false,
    permissions: [
      PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages,
      PermissionFlagsBits.EmbedLinks, PermissionFlagsBits.AttachFiles,
      PermissionFlagsBits.ReadMessageHistory, PermissionFlagsBits.AddReactions,
      PermissionFlagsBits.Connect, PermissionFlagsBits.Speak,
    ],
  },
  {
    name: 'Verified User',
    color: '#F1C40F',
    position: 4,
    hoist: false,
    mentionable: false,
    permissions: [
      PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages,
      PermissionFlagsBits.EmbedLinks, PermissionFlagsBits.AttachFiles,
      PermissionFlagsBits.ReadMessageHistory, PermissionFlagsBits.AddReactions,
      PermissionFlagsBits.Connect, PermissionFlagsBits.Speak,
    ],
  },
  {
    name: 'Member',
    color: '#95A5A6',
    position: 3,
    hoist: false,
    mentionable: false,
    permissions: [
      PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages,
      PermissionFlagsBits.ReadMessageHistory, PermissionFlagsBits.AddReactions,
      PermissionFlagsBits.Connect, PermissionFlagsBits.Speak,
    ],
  },
  {
    name: 'Unverified',
    color: '#636E72',
    position: 2,
    hoist: false,
    mentionable: false,
    permissions: [
      PermissionFlagsBits.ViewChannel, PermissionFlagsBits.ReadMessageHistory,
    ],
  },
  {
    name: 'Muted',
    color: '#2C3E50',
    position: 1,
    hoist: false,
    mentionable: false,
    permissions: [
      PermissionFlagsBits.ViewChannel, PermissionFlagsBits.ReadMessageHistory,
    ],
  },
];
